[build]
  functions = "netlify/functions"
  publish = "public"
  command = "npx pnpm i --store=node_modules/.pnpm-store && npx pnpm run build"

[build.environment]
  NPM_FLAGS = "--prefix=/dev/null"
  NODE_VERSION = "16"

[dev]
  functions = "netlify/functions"
  publish = "public"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[[headers]]
  for = "/build/*"
  [headers.values]
    "Cache-Control" = "public, max-age=31536000, s-maxage=31536000"
